name: Build and Deploy

on:
  push:
    branches:
      - main  # Executa o build quando houver um push para o branch main
  pull_request:
    branches:
      - main  # Executa o build quando um PR for feito para o branch main

jobs:
  build:
    runs-on: ubuntu-latest  # Especifica que o workflow rodará em um sistema Ubuntu

    steps:
      - name: Check out repository
        uses: actions/checkout@v2  # Faz o checkout do repositório

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Configura o Node.js
        with:
          node-version: '16'  # Versão do Node.js que você está usando (alterado para v16)

      - name: Cache Yarn dependencies
        uses: actions/cache@v2  # Cache de dependências do Yarn
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install  # Instala as dependências usando Yarn

      - name: Build project
        run: yarn build  # Executa o build do projeto usando Yarn

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3  # Atualiza para a versão v3 da ação
        with:
          name: build-artifact  # Nome do artefato
          path: ./dist  # Caminho para os arquivos de build (geralmente a pasta 'dist' ou 'build')

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4  # Usando a versão mais recente estável v4
        with:
          branch: gh-pages  # A branch onde o conteúdo será publicado
          folder: dist  # A pasta com o build (por exemplo, dist)

